# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-06 12:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='audit_kahasra',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('mohalla_name', models.CharField(default=None, max_length=50, null=True)),
                ('plot_no', models.CharField(default=None, max_length=50, null=True)),
                ('area_total_resi', models.FloatField(default=0.0, max_length=10)),
                ('area_total_non_resi', models.FloatField(default=0.0, max_length=10)),
                ('area_free', models.FloatField(default=0.0, max_length=10)),
                ('plot_desc', models.CharField(default=None, max_length=100, null=True)),
                ('holder_name', models.CharField(default=None, max_length=500, null=True)),
                ('revenue_resi', models.FloatField(default=0.0, max_length=10)),
                ('revenue_non_resi', models.FloatField(default=0.0, max_length=10)),
                ('lease_expiry_date', models.DateTimeField(null=True)),
                ('remarks', models.TextField(default=None, null=True)),
                ('page_no', models.IntegerField(default=None, null=True)),
                ('mutation_id', models.IntegerField(default=None, null=True)),
                ('per_plot_area', models.TextField(default=None, null=True)),
                ('curr_date', models.DateTimeField(auto_now=True)),
                ('operation', models.CharField(default=None, max_length=7, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='blocks',
            fields=[
                ('block_id', models.IntegerField(primary_key=True, serialize=False)),
                ('block_name', models.CharField(default=None, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='khasra',
            fields=[
                ('khasra_id', models.AutoField(primary_key=True, serialize=False)),
                ('mohalla_name', models.CharField(default=None, max_length=50, null=True)),
                ('plot_no', models.CharField(default=None, max_length=50, null=True)),
                ('area_total_resi', models.FloatField(default=0.0, max_length=10)),
                ('area_total_non_resi', models.FloatField(default=0.0, max_length=10)),
                ('area_free', models.FloatField(default=0.0, max_length=10)),
                ('plot_desc', models.CharField(default=None, max_length=100, null=True)),
                ('holder_name', models.CharField(default=None, max_length=500, null=True)),
                ('revenue_resi', models.FloatField(default=0.0, max_length=10)),
                ('revenue_non_resi', models.FloatField(default=0.0, max_length=10)),
                ('lease_expiry_date', models.DateTimeField(null=True)),
                ('case_no', models.CharField(default=None, max_length=100, null=True)),
                ('adesh_date', models.DateTimeField(default=None, null=True)),
                ('remarks', models.TextField(default=None, null=True)),
                ('corrected_entry', models.TextField(default=None, null=True)),
                ('arrears_year', models.CharField(default='2009-2010', max_length=9, null=True)),
                ('arrear', models.FloatField(default=0.0, max_length=10)),
                ('page_no', models.IntegerField(default=None, null=True)),
                ('mutation_id', models.IntegerField(default=None, null=True)),
                ('is_govt', models.IntegerField(default=0)),
                ('per_plot_area', models.TextField(default=None, null=True)),
                ('islock', models.IntegerField(default=0, null=True)),
                ('operation', models.IntegerField(default=0, null=True)),
                ('curr_date', models.DateTimeField(default=None, null=True)),
                ('entry_date', models.DateTimeField(default=None, null=True)),
                ('block_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='lease.blocks')),
                ('user_id', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='print_count',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('print_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='transaction',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('acc_id', models.IntegerField(default=True)),
                ('payment_by', models.CharField(default=None, max_length=30, null=True)),
                ('payment_no', models.CharField(default=None, max_length=30, null=True)),
                ('payment_date', models.DateTimeField(auto_now=True)),
                ('is_20yr_free', models.IntegerField(default=0, null=True)),
                ('is_free_hold', models.IntegerField(default=0, null=True)),
                ('depositior_name', models.CharField(default=None, max_length=50, null=True)),
                ('depositior_mob', models.CharField(default=None, max_length=15, null=True)),
                ('curr_date', models.DateTimeField(default=None, null=True)),
                ('remark', models.TextField(default=None, null=True)),
                ('user_id', models.ForeignKey(default=None, max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='print_count',
            name='acc_id',
            field=models.ForeignKey(default=None, max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, to='lease.transaction'),
        ),
        migrations.AddField(
            model_name='print_count',
            name='user_name',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='audit_kahasra',
            name='block_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='lease.blocks'),
        ),
    ]
