# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-06 17:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lease', '0001_first_database_commit'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='audit_kahasra',
            new_name='audit_khasra',
        ),
    ]
